images:
  tags:
    registry: "localhost:5000"
    contrail_version: 4.0.2.0-35
    nodemgr: "contrail-nodemgr"
    agent_vrouter: "contrail-agent-vrouter"
    analytics_api: "contrail-analytics-api"
    analytics_collector: "contrail-analytics-collector"
    analytics_alarm_gen: "contrail-analytics-alarm-gen"
    analytics_query_engine: "contrail-analytics-query-engine"
    analytics_snmp_collector: "contrail-analytics-snmp-collector"
    analytics_topology: "contrail-analytics-topology"
    control_control: "contrail-controller-control-control"
    control_dns: "contrail-controller-control-dns"
    control_named: "contrail-controller-control-named"
    config_api: "contrail-controller-config-api"
    config_devicemgr: "contrail-controller-config-devicemgr"
    config_schema_transformer: "contrail-controller-config-schema"
    config_svcmonitor: "contrail-controller-config-svcmonitor"
    webui_job: "contrail-controller-webui-job"
    webui_web: "contrail-controller-webui-web"
    kafka: "contrail-external-kafka"
    cassandra: "cassandra:3.11.1"
    redis: "redis:4.0.2"
    zookeeper: "zookeeper:3.4.10"
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
  imagePullPolicy: "IfNotPresent"

labels:
  analyticsdb:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  configdb:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  zookeeper:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  redis:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  kafka:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  controller:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  analytics:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  agent:
    node_selector_key: openstack-compute-node
    node_selector_value: enabled

dependencies:
  analyticsdb:
    daemonset:
    - zookeeper
    - kafka
  configdb:
    daemonset:
    - zookeeper
    - kafka
  agent:
    daemonset:
    - contrail-config
  config:
    daemonset:
    - contrail-configdb
  analytics:
    daemonset:
    - contrail-analyticsdb
  control:
    daemonset:
    - contrail-config
  webui:
    daemonset:
    - contrail-config
    - redis

conf:
  # host_os - (OPTIONAL) host operating system release. Sample values "ubuntu" and "centos". Default is ubuntu
  host_os: ubuntu
  controller_nodes:
  log_level: SYS_NOTICE

  cloud_orchestrator: openstack
  aaa_mode: cloud-admin

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  namespace: openstack
  cluster_domain_suffix: cluster.local
  identity:
    name: keystone
    auth:
      admin:
        region_name: RegionOne
        username: admin
        password: password
        project_name: admin
        user_domain_name: default
        project_domain_name: default
    hosts:
      default: keystone-api
      public: keystone
    host_fqdn_override:
      default: null
    path:
      default: /v3
    scheme:
      default: http
    port:
      admin:
        default: 35357
      api:
        default: 80
# TODO: pass network URL to webui
  network:
    name: neutron
    hosts:
      default: neutron-server
      public: neutron
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: 'http'
    port:
      api:
        default: 9696
        public: 80
# TODO: pass compute URL to webui
  compute:
    name: nova
    hosts:
      default: nova-api
      public: nova
    host_fqdn_override:
      default: null
    path:
      default: "/v2/%(tenant_id)s"
    scheme:
      default: 'http'
    port:
      api:
        default: 8774
        public: 80
      novncproxy:
        default: 6080
# TODO: pass image URL to webui
  image:
    name: glance
    hosts:
      default: glance-api
      public: glance
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: http
    port:
      api:
        default: 9292
        public: 80
  oslo_messaging:
    auth:
      admin:
        username: admin
        password: password
      user:
        username: rabbitmq
        password: password
    hosts:
      default: rabbitmq
    host_fqdn_override:
      default: null
    path: /
    scheme: rabbit
    port:
      amqp:
        default: 5672

manifests:
  daemonset_configmap: true
  daemonset_config: true
  daemonset_configdb: true
  daemonset_control: true
  daemonset_webui: true
  daemonset_analytics: true
  daemonset_analyticsdb: true
  daemonset_agent: true
  daemonset_redis: true
  daemonset_zookeeper: true
  daemonset_kafka: true
