images:
  tags:
    agent_vrouter: "localhost:5000/contrail-agent-vrouter:4.0.2.0-35"
    agent_nodemgr: "localhost:5000/contrail-agent-nodemgr:4.0.2.0-35"
    analytics_api: "localhost:5000/contrail-analytics-api:4.0.2.0-35"
    analytics_collector: "localhost:5000/contrail-analytics-collector:4.0.2.0-35"
    analytics_alarm_gen: "localhost:5000/contrail-analytics-alarm-gen:4.0.2.0-35"
    analytics_query_engine: "localhost:5000/contrail-analytics-query-engine:4.0.2.0-35"
    analytics_snmp_collector: "localhost:5000/contrail-analytics-snmp-collector:4.0.2.0-35"
    analytics_topology: "localhost:5000/contrail-analytics-topology:4.0.2.0-35"
    analytics_nodemgr: "localhost:5000/contrail-analytics-nodemgr:4.0.2.0-35"
    control_control: "localhost:5000/contrail-controller-control-control:4.0.2.0-35"
    control_dns: "localhost:5000/contrail-controller-control-dns:4.0.2.0-35"
    control_named: "localhost:5000/contrail-controller-control-named:4.0.2.0-35"
    control_nodemgr: "localhost:5000/contrail-controller-control-nodemgr:4.0.2.0-35"
    config_api: "localhost:5000/contrail-controller-config-api:4.0.2.0-35"
    config_devicemgr: "localhost:5000/contrail-controller-config-devicemgr:4.0.2.0-35"
    config_schema_transformer: "localhost:5000/contrail-controller-config-schema:4.0.2.0-35"
    config_svcmonitor: "localhost:5000/contrail-controller-config-svcmonitor:4.0.2.0-35"
    config_nodemgr: "localhost:5000/contrail-controller-config-nodemgr:4.0.2.0-35"
    webui_job: "localhost:5000/contrail-controller-webui-job:4.0.2.0-35"
    webui_web: "localhost:5000/contrail-controller-webui-web:4.0.2.0-35"
    kafka: "localhost:5000/contrail-analyticsdb-kafka:4.0.2.0-35"
    cassandra: "cassandra:2.2.10"
    redis: "redis:4.0.2"
    zookeeper: "zookeeper:3.4.10"
  imagePullPolicy: "IfNotPresent"

labels:
  controller:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  analytics:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  analyticsdb:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  agent:
    node_selector_key: openstack-compute-node
    node_selector_value: enabled

conf:
  # host_os - (OPTIONAL) host operating system release. Sample values "ubuntu" and "centos". Default is ubuntu
  host_os: ubuntu
  controller_nodes: 10.87.65.153

  keystone_config:
     KEYSTONE:
       version: v3
       admin_port: 35357
       public_port: 80
       auth_protocol: http
       admin_user: admin
       admin_password: password
       admin_tenant: admin
       insecure: True
       user_domain_name: Default
       project_domain_name: Default


# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  namespace: openstack
  cluster_domain_suffix: cluster.local
  identity:
    name: keystone
    hosts:
      default: keystone-api
      public: keystone
    host_fqdn_override:
      default: null
    path:
      default: /v3
    scheme:
      default: http
    port:
      admin:
        default: 35357
      api:
        default: 80
  network:
    name: neutron
    hosts:
      default: neutron-server
      public: neutron
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: 'http'
    port:
      api:
        default: 9696
        public: 80
  compute:
    name: nova
    hosts:
      default: nova-api
      public: nova
    host_fqdn_override:
      default: null
    path:
      default: "/v2/%(tenant_id)s"
    scheme:
      default: 'http'
    port:
      api:
        default: 8774
        public: 80
      novncproxy:
        default: 6080
  compute_metadata:
    name: nova
    hosts:
      default: nova-metadata
      public: metadata
    host_fqdn_override:
      default: null
    path:
      default: /
    scheme:
      default: 'http'
    port:
      metadata:
        default: 8775
        public: 80
  image:
    name: glance
    hosts:
      default: glance-api
      public: glance
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: http
    port:
      api:
        default: 9292
        public: 80

manifests:
  daemonset_controller: true
  daemonset_analytics: true
  daemonset_analyticsdb: true
  daemonset_agent: true
