apiVersion: v1
name: opencontrail-controller
description: A Helm chart for OpenContrail Controller
version: 0.1.0
appVersion: Contrail 4.0.2
home: https://github.com/Juniper/contrail-docker/
sources:
  - https://github.com/Juniper/contrail-controller/
tillerVersion: ">=2.4.0"
keywords:
  - OpenContrail
  - SDN
