{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.deployment_server }}
{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.server }}

{{- $mounts_neutron_server := .Values.pod.mounts.neutron_server.neutron_server }}
{{- $mounts_neutron_server_init := .Values.pod.mounts.neutron_server.init_container }}
{{- $neutron_plugin := .Values.conf.plugins.neutron_plugin_framework }}
{{- $neutron_plugin_conf := .Values.conf.plugins.neutron_plugin_conf }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: neutron-server
spec:
  replicas: {{ .Values.pod.replicas.server }}
{{ tuple $envAll | include "helm-toolkit.snippets.kubernetes_upgrades_deployment" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "neutron" "server" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      affinity:
{{ tuple $envAll "neutron" "server" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
      nodeSelector:
        {{ .Values.labels.server.node_selector_key }}: {{ .Values.labels.server.node_selector_value }}
      terminationGracePeriodSeconds: {{ .Values.pod.lifecycle.termination_grace_period.server.timeout | default "30" }}
      initContainers:
{{ tuple $envAll $dependencies $mounts_neutron_server_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
{{- if .Values.images.tags.plugin }}
        - name: neutron-plugin-init
          image: {{ .Values.images.tags.plugin }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          securityContext:
            runAsUser: {{ .Values.pod.user.neutron.uid }}
          volumeMounts:
            - name: neutron-plugin-shared
              mountPath: /opt/plugin
{{- end }}
      containers:
        - name: neutron-server
          image: {{ .Values.images.tags.neutron_server }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
{{ tuple $envAll $envAll.Values.pod.resources.server | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          securityContext:
            runAsUser: {{ .Values.pod.user.neutron.uid }}
          command:
            - /tmp/neutron-server.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /tmp/neutron-server.sh
                  - stop
          ports:
            - containerPort: {{ .Values.network.server.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.network.server.port }}
          volumeMounts:
{{/*
  In general should be a base ml2 init container for base scenario.
  It should copy vanilla neutron-server.sh to shared volume.
*/}}
{{- if .Values.images.tags.plugin }}
            - name: neutron-plugin-shared
              mountPath: /tmp/neutron-server.sh
              subPath: neutron-server.sh
              readOnly: true
{{- else }}
            - name: neutron-bin
              mountPath: /tmp/neutron-server.sh
              subPath: neutron-server.sh
              readOnly: true
{{- end }}
            - name: neutron-etc
              mountPath: /etc/neutron/neutron.conf
              subPath: neutron.conf
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/plugins/{{ $neutron_plugin }}/{{ $neutron_plugin_conf }}
              subPath: {{ $neutron_plugin_conf }}
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/api-paste.ini
              subPath: api-paste.ini
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/policy.json
              subPath: policy.json
              readOnly: true
{{- if .Values.images.tags.plugin }}
            - name: neutron-plugin-shared
              mountPath: /opt/plugin
              readOnly: true
{{- end }}
{{ if $mounts_neutron_server.volumeMounts }}{{ toYaml $mounts_neutron_server.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: neutron-bin
          configMap:
            name: neutron-bin
            defaultMode: 0555
        - name: neutron-etc
          configMap:
            name: neutron-etc
            defaultMode: 0444
{{- if .Values.images.tags.plugin }}
        - name: neutron-plugin-shared
          emptyDir: {}
{{- end }}
{{ if $mounts_neutron_server.volumes }}{{ toYaml $mounts_neutron_server.volumes | indent 8 }}{{ end }}
{{- end }}
