{{- if .Values.manifests.daemonset_configmap }}
{{- $envAll := . }}

{{- $identityURI := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.host_and_port_endpoint_uri_lookup" }}
{{- $identityURIParts := split ":" $identityURI -}}

{{- $rabbitmqURI := tuple "oslo_messaging" "internal" "amqp" . | include "helm-toolkit.endpoints.host_and_port_endpoint_uri_lookup" }}
{{- $rabbitmqURIParts := split ":" $rabbitmqURI -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-contrail
data:
  CONTROLLER_NODES: {{ .Values.conf.controller_nodes }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-auth
data:
  CLOUD_ORCHESTRATOR: {{ .Values.conf.cloud_orchestrator }}
  AAA_MODE: {{ .Values.conf.aaa_mode }}
  KEYSTONE_AUTH_ADMIN_USER: {{ .Values.endpoints.identity.auth.admin.username }}
  KEYSTONE_AUTH_ADMIN_TENANT: {{ .Values.endpoints.identity.auth.admin.project_name }}
  KEYSTONE_AUTH_ADMIN_PASSWORD: {{ .Values.endpoints.identity.auth.admin.password }}
  KEYSTONE_AUTH_USER_DOMAIN_NAME: {{ .Values.endpoints.identity.auth.admin.user_domain_name }}
  KEYSTONE_AUTH_PROJECT_DOMAIN_NAME: {{ .Values.endpoints.identity.auth.admin.project_domain_name }}
  KEYSTONE_AUTH_URL_VERSION: {{ .Values.endpoints.identity.path.default }}
  KEYSTONE_AUTH_HOST: {{ $identityURIParts._0 }}
  KEYSTONE_AUTH_PROTO: {{ .Values.endpoints.identity.scheme.default }}
  KEYSTONE_AUTH_ADMIN_PORT: {{ .Values.endpoints.identity.port.admin.default | quote }}
  KEYSTONE_AUTH_PUBLIC_PORT: {{ .Values.endpoints.identity.port.api.default | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-rabbitmq
data:
  RABBITMQ_NODES: {{ $rabbitmqURIParts._0 }}
  RABBITMQ_PORT: {{ .Values.endpoints.oslo_messaging.port.amqp.default | quote }}
  RABBITMQ_USER: {{ .Values.endpoints.oslo_messaging.auth.user.username | quote }}
  RABBITMQ_PASSWORD: {{ .Values.endpoints.oslo_messaging.auth.user.password | quote }}
{{- end }}
