{{- if .Values.manifests.daemonset_controller }}
{{- $envAll := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-configdb
data:
# TODO: fix seeds and listen address
  CASSANDRA_SEEDS: {{ .Values.conf.controller_nodes }}
  CASSANDRA_CLUSTER_NAME: ContrailConfigDB
  CASSANDRA_START_RPC: "true"
  CASSANDRA_LISTEN_ADDRESS: {{ .Values.conf.controller_nodes }}
  JVM_EXTRA_OPTS: >-
    -Dcassandra.rpc_port=9161
    -Dcassandra.native_transport_port=9041
    -Dcassandra.ssl_storage_port=7011
    -Dcassandra.storage_port=7010
    -Dcassandra.jmx.local.port=7200
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-configdb
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "opencontrail" "controller" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.controller.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.controller.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-configdb
        image: {{ .Values.images.tags.cassandra | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-configdb
        volumeMounts:
        - mountPath: /var/lib/cassandra
          name: configdb-data
      volumes:
      - name: configdb-data
        hostPath:
          path: /var/lib/configdb
{{- end }}
