{{- if .Values.manifests.daemonset_controller }}
{{- $envAll := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: control-env
data:
  CONTROLLER_NODES: {{ .Values.conf.controller_nodes }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-control
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "opencontrail" "controller" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.controller.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.controller.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-control
        image: {{ .Values.images.tags.control_control | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: control-env
        - configMapRef:
            name: configmap-auth
        - configMapRef:
            name: configmap-rabbitmq
      - name: contrail-dns
        image: {{ .Values.images.tags.control_dns | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: control-env
        - configMapRef:
            name: configmap-auth
        - configMapRef:
            name: configmap-rabbitmq
      - name: contrail-named
        image: {{ .Values.images.tags.control_named | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: control-env
        - configMapRef:
            name: configmap-auth
        - configMapRef:
            name: configmap-rabbitmq
      - name: contrail-control-nodemgr
        image: {{ .Values.images.tags.nodemgr | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: control-env
        - configMapRef:
            name: configmap-auth
        env:
        - name: NODE_TYPE
          value: control
        - name: DOCKER_HOST
          value: "unix://mnt/docker.sock"
# todo: there is type Socket in new kubernetes, it is possible to use full
# path:
# hostPath:
#   path: /var/run/docker.sock and
#   type: Socket
        volumeMounts:
        - mountPath: /mnt
          name: docker-unix-socket
      volumes:
      - name: docker-unix-socket
        hostPath:
          path: /var/run
{{- end }}
