{{- if .Values.manifests.daemonset_zookeeper }}
{{- $envAll := . }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: zookeeper
spec:
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.controller.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.controller.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      initContainers:
{{ tuple $envAll .Values.dependencies.zookeeper [] | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
      - name: zookeeper
        image: {{ .Values.images.tags.zookeeper | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        volumeMounts:
        - mountPath: /var/lib/zookeeper
          name: zookeeper-config-data
      volumes:
      - name: zookeeper-config-data
        hostPath:
          path: /var/lib/config_zookeeper_data
{{- end }}
