{{- if .Values.manifests.daemonset_analyticsdb }}
{{- $envAll := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-analyticsdb
data:
# TODO: fix seeds and listen address
  CASSANDRA_SEEDS: {{ .Values.conf.controller_nodes }}
  CASSANDRA_CLUSTER_NAME: Contrail
  CASSANDRA_START_RPC: "true"
  CASSANDRA_LISTEN_ADDRESS: {{ .Values.conf.controller_nodes }}
  JVM_EXTRA_OPTS: >-
    -Dcassandra.rpc_port=9160
    -Dcassandra.native_transport_port=9042
    -Dcassandra.ssl_storage_port=7001
    -Dcassandra.storage_port=7000
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-analyticsdb
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "opencontrail" "analyticsdb" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.analyticsdb.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.analyticsdb.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-analyticsdb
        image: {{ .Values.images.tags.cassandra | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-analyticsdb
        volumeMounts:
        - mountPath: /var/lib/cassandra
          name: analyticsdb-data
      volumes:
      - name: analyticsdb-data
        hostPath:
          path: /var/lib/analyticsdb
{{- end }}
