{{- if .Values.manifests.daemonset_controller }}
{{- $envAll := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-env
data:
  CONTROLLER_NODES: {{ .Values.conf.controller_nodes }}
  RABBITMQ_NODES: rabbitmq.openstack.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: rabbitmq
  RABBITMQ_PASSWORD: password
  CONFIG_API_AUTH: keystone
  CONFIG_API_AAA_MODE: cloud-admin
  ANALYTICS_API_AAA_MODE: cloud-admin
  CONFIG_AUTHN_SERVER: keystone-api.openstack.svc.cluster.local
  ADMIN_USER: admin
  ADMIN_TENANT: admin
  ADMIN_PASSWORD: password
  AUTH_URL_VERSION: v3
  AUTH_URL_TOKENS: /v3/auth/tokens
  DOCKER_HOST: "unix://mnt/docker.sock"
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-config
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "opencontrail" "controller" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.controller.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.controller.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-controller-config-api
        image: {{ .Values.images.tags.config_api | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: config-env
      - name: contrail-controller-config-devicemgr
        image: {{ .Values.images.tags.config_devicemgr | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: config-env
      - name: contrail-controller-config-schema
        image: {{ .Values.images.tags.config_schema_transformer | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: config-env
      - name: contrail-controller-config-svcmonitor
        image: {{ .Values.images.tags.config_svcmonitor | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: config-env
      - name: contrail-controller-config-nodemgr
        image: {{ .Values.images.tags.config_nodemgr | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: config-env
# todo: there is type Socket in new kubernetes, it is possible to use full
# path:
# hostPath:
#   path: /var/run/docker.sock and
#   type: Socket
        volumeMounts:
        - mountPath: /mnt
          name: docker-unix-socket
      volumes:
      - name: docker-unix-socket
        hostPath:
          path: /var/run
{{- end }}
