{{- if .Values.manifests.daemonset_controller }}
{{- $envAll := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-webui-env
data:
  CONTROLLER_NODES: {{ .Values.conf.controller_nodes }}
  orchestration_Manager: openstack
  identityManager_ip: keystone-api.openstack.svc.cluster.local
  identityManager_port: "80"
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-webui
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "opencontrail" "controller" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.controller.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.controller.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-webui-job
        image: {{ .Values.images.tags.webui_job | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: config-webui-env
      - name: contrail-webui-web
        image: {{ .Values.images.tags.webui_web | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: config-webui-env
{{- end }}
