{{- if .Values.manifests.daemonset_redis }}
{{- $envAll := . }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: redis
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "opencontrail" "redis" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.analyticsdb.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.analyticsdb.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      initContainers:
{{ tuple $envAll .Values.dependencies.redis "[]" | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
      - name: redis
        image: {{ .Values.images.tags.redis | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
{{- end }}
