{{- if .Values.manifests.daemonset_analyticsdb }}
{{- $envAll := . }}
# host_os is a mandatory field
{{- $_ := required ".Values.conf.host_os must be specified, valid values are ubuntu, centos" .Values.conf.host_os }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-analyticsdb
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "opencontrail" "analyticsdb" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.analyticsdb.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.analyticsdb.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-analyticsdb
        image: {{ .Values.images.tags.analyticsdb }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: contrailctl-analyticsdb
          mountPath: /etc/contrailctl/analyticsdb.conf
          subPath: analyticsdb.conf
        - name: analyticsdb-data
          mountPath: /var/lib/cassandra
        - name: zookeeper-analyticsdb-data
          mountPath: /var/lib/zookeeper
      volumes:
      - name: contrailctl-analyticsdb
        configMap:
          name: configmap-contrailctl
          defaultMode: 0444
      - name: analyticsdb-data
        hostPath:
          path: /var/lib/analyticsdb
      - name: zookeeper-analyticsdb-data
        hostPath:
          path: /var/lib/analyticsdb_zookeeper_data
{{- end }}
