{{- if .Values.manifests.daemonset_analytics }}
{{- $envAll := . }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-analytics
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "opencontrail" "analytics" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.analytics.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.analytics.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-analytics-api
        image: {{ .Values.images.tags.analytics_api | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-contrail
        - configMapRef:
            name: configmap-auth
      - name: contrail-collector
        image: {{ .Values.images.tags.analytics_collector | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-contrail
        - configMapRef:
            name: configmap-auth
      - name: contrail-alarm-gen
        image: {{ .Values.images.tags.analytics_alarm_gen | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-contrail
        - configMapRef:
            name: configmap-auth
        - configMapRef:
            name: configmap-rabbitmq
      - name: contrail-query-engine
        image: {{ .Values.images.tags.analytics_query_engine | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-contrail
        - configMapRef:
            name: configmap-auth
      - name: contrail-snmp-collector
        image: {{ .Values.images.tags.analytics_snmp_collector | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-contrail
        - configMapRef:
            name: configmap-auth
      - name: contrail-topology
        image: {{ .Values.images.tags.analytics_topology | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-contrail
        - configMapRef:
            name: configmap-auth
      - name: contrail-analytics-nodemgr
        image: {{ .Values.images.tags.nodemgr | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-contrail
        - configMapRef:
            name: configmap-auth
        env:
        - name: NODE_TYPE
          value: analytics
        - name: DOCKER_HOST
          value: "unix://mnt/docker.sock"
# todo: there is type Socket in new kubernetes, it is possible to use full
# path:
# hostPath:
#   path: /var/run/docker.sock and
#   type: Socket
        volumeMounts:
        - mountPath: /mnt
          name: docker-unix-socket
      volumes:
      - name: docker-unix-socket
        hostPath:
          path: /var/run
{{- end }}
