- project:
    name: openstack/openstack-helm
    check:
      jobs:
        - openstack-helm-aio-basic-nfs-opencontrail-pvc:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-helm-aio-basic-nfs-ovs-pvc:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
