{{- if .Values.manifests.daemonset_vrouter_agent }}
{{- $envAll := . }}
{{- $cloud_orchestrator := .Values.conf.global_config.GLOBAL.cloud_orchestrator }}
# host_os is a mandatory field
{{- $_ := required ".Values.conf.host_os must be specified, valid values are ubuntu, centos" .Values.conf.host_os }}
{{- $host_os := .Values.conf.host_os }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-vrouter-agent
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "opencontrail" "vrouter-agent" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.vrouter_agent.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.vrouter_agent.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      automountServiceAccountToken: false
      initContainers:
{{- if eq $host_os "centos" }}
{{- $_ := required ".Values.images.tags.vrouter_compiler must be specified, if hostOS is centos" .Values.images.vrouter_compiler }}
      - name: contrail-vrouter-compiler
        image: {{ .Values.images.tags.vrouter_compiler | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /usr/src/kernels
          name: usr-src-kernels
        env:
        - name: INSTALL_VROUTER_MODULE
          value: 'true'
{{- end }}
{{- if eq $cloud_orchestrator "kubernetes" }}
      - name: contrail-kubernetes-agent
        image: {{ .Values.images.tags.kubernetes_agent | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: tmp-contrail-config
          mountPath: /tmp/contrailctl/global.conf
          subPath: global.conf
        - name: tmp-contrail-config
          mountPath: /tmp/contrailctl/kubernetesagent.conf
          subPath: kubernetesagent.conf
        - name: contrail-varlib
          mountPath: /var/lib/contrail/
        - name: etc-cni
          mountPath: /host/etc_cni
        - name: opt-cni-bin
          mountPath: /host/opt_cni_bin
        - name: var-log-contrail-cni
          mountPath: /var/log/contrail/cni
{{- end }}
{{- if eq $cloud_orchestrator "openstack" }}
      - name: register-vrouter-to-controller
        image: {{ .Values.images.tags.register_vrouter | quote }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        command:
        - /tmp/register-vrouter.sh
        env:
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: register-vrouter
          mountPath: /tmp/register-vrouter.sh
          subPath: register-vrouter.sh
{{- end }}
      containers:
      - name: contrail-agent
        image: {{ .Values.images.tags.vrouter_agent | quote }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: tmp-contrail-config
          mountPath: /tmp/contrailctl/global.conf
          subPath: global.conf
        - name: tmp-contrail-config
          mountPath: /tmp/contrailctl/agent.conf
          subPath: agent.conf
        - name: tmp-contrail-config
          mountPath: /tmp/contrailctl/kubemanager.conf
          subPath: kubemanager.conf
        - name: contrail-bin
          mountPath: /tmp/vrouter-agent-readiness.sh
          subPath: vrouter-agent-readiness.sh
        - name: lib-modules
          mountPath: /lib/modules
        - name: usr-src
          mountPath: /usr/src
        - name: contrail-varlib
          mountPath: /var/lib/contrail/
{{- if eq $cloud_orchestrator "kubernetes" }}
        - name: pod-secret
          mountPath: /tmp/serviceaccount
        - name: opt-cni-bin
          mountPath: /host/opt_cni_bin
        - name: etc-cni
          mountPath: /host/etc_cni
        # This is a workaround just to make sure the directory is created on host
        - name: var-log-contrail-cni
          mountPath: /var/log/contrail/cni
{{- end }}
        readinessProbe:
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 500
          exec:
            command:
              - /tmp/vrouter-agent-readiness.sh
      volumes:
      - name: tmp-contrail-config
        configMap:
          name: contrailctl-vrouter-config
          defaultMode: 0444
      - name: contrail-bin
        configMap:
          name: vrouter-bin
          defaultMode: 0555
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: contrail-varlib
        hostPath:
          path: /var/lib/contrail/
{{- if eq $host_os "centos" }}
      - name: usr-src-kernels
        hostPath:
          path: /usr/src/kernels
{{- end }}
{{- if eq $cloud_orchestrator "kubernetes" }}
      - name: pod-secret
        secret:
          secretName: contrail-vrouter-token
      - name: opt-cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: etc-cni
        hostPath:
          path: /etc/cni
      - name: var-log-contrail-cni
        hostPath:
          path: /var/log/contrail/cni/
{{- end }}
{{- if eq $cloud_orchestrator "openstack"}}
      - name: register-vrouter
        configMap:
          name: vrouter-bin
          defaultMode: 0555
{{- end }}
{{- end }}
